version: '3.8'

services:
  zenith:
    build: .
    ports:
      - '3000:80'
    container_name: zenith
    restart: unless-stopped
    environment:
      - NODE_ENV=production
  zenith-dev:
    build:
      context: .
      target: builder
    ports:
      - '3001:3000'
    container_name: zenith-dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
    profiles:
      - dev
